import { IPoliticalParty, IPoliticalPartyState } from '../app/data/schema/political-party';

export const PoliticalPartyStateDefaultMock: IPoliticalPartyState = {
  selectedParty: {} as IPoliticalParty,
  parties: [
    {
      imageUrl: 'https://seeklogo.com/images/P/Praha-logo-D9CC980EDF-seeklogo.com.png',
      name: 'Praha sobě',
      id: '1',
      tags: ['Praha', 'Praha sobě', 'Demokracie'],
      politicians: [
        {
          id: '1',
          birthDate: new Date('1975'),
          fullName: 'Ainsley Barker',
          profileImageUrl: 'https://google.com',
          facebookUrl: 'https://facebook.com',
          instagramUrl: 'https://instagram.com',
          twitterUrl: 'https://twitter.com',
        },
        {
          id: '2',
          birthDate: new Date('1980'),
          fullName: 'Nelson Arias',
          profileImageUrl: 'https://google.com',
          facebookUrl: 'https://facebook.com',
          instagramUrl: 'https://instagram.com',
          twitterUrl: 'https://twitter.com',
        },
        {
          id: '3',
          birthDate: new Date('1982'),
          fullName: 'Scarlett Klein',
          profileImageUrl: 'https://google.com',
          facebookUrl: 'https://facebook.com',
          instagramUrl: 'https://instagram.com',
          twitterUrl: 'https://twitter.com',
        },
        {
          id: '4',
          birthDate: new Date('1955'),
          fullName: 'Madden Pittman',
          profileImageUrl: 'https://google.com',
          facebookUrl: 'https://facebook.com',
          instagramUrl: 'https://instagram.com',
          twitterUrl: 'https://twitter.com',
        },
      ],
    },
    {
      imageUrl:
        'https://e7.pngegg.com/pngimages/31/978/png-clipart-peace-sign-logo-angellist-peace-logo-icons-logos-emojis-tech-companies-thumbnail.png',
      name: 'OWF',
      id: '2',
      tags: ['Peace', 'Human rights', 'Whatever'],
      politicians: [
        {
          id: '1',
          birthDate: new Date('1975'),
          fullName: 'Josef Baker',
          profileImageUrl: 'https://google.com',
          facebookUrl: 'https://facebook.com',
          instagramUrl: 'https://instagram.com',
          twitterUrl: 'https://twitter.com',
        },
        {
          id: '2',
          birthDate: new Date('1980'),
          fullName: 'Andrej Ari',
          profileImageUrl: 'https://google.com',
          facebookUrl: 'https://facebook.com',
          instagramUrl: 'https://instagram.com',
          twitterUrl: 'https://twitter.com',
        },
        {
          id: '3',
          birthDate: new Date('1982'),
          fullName: 'Scarlett Hemmer',
          profileImageUrl: 'https://google.com',
          facebookUrl: 'https://facebook.com',
          instagramUrl: 'https://instagram.com',
          twitterUrl: 'https://twitter.com',
        },
        {
          id: '4',
          birthDate: new Date('1955'),
          fullName: 'Madden Dog',
          profileImageUrl: 'https://google.com',
          facebookUrl: 'https://facebook.com',
          instagramUrl: 'https://instagram.com',
          twitterUrl: 'https://twitter.com',
        },
        {
          id: '5',
          birthDate: new Date('1955'),
          fullName: 'John Brown',
          profileImageUrl: 'https://google.com',
          facebookUrl: 'https://facebook.com',
          instagramUrl: 'https://instagram.com',
          twitterUrl: 'https://twitter.com',
        },
      ],
    },
  ],
};
